# Generated by Django 4.1.5 on 2023-06-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
