# Generated by Django 4.1.5 on 2023-06-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_contact_created_alter_customer_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.customer",
            ),
        ),
    ]
