# Generated by Django 4.1.5 on 2023-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_contact_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
