# Generated by Django 4.1.5 on 2023-06-29 20:58

from django.db import migrations, models
import django.db.models.deletion
import internal.crm.models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_contact_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("objects", internal.crm.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.customer",
            ),
        ),
    ]
