# Generated by Django 4.1.5 on 2023-06-29 21:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_contact_managers_customer_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=20, null=True, region=None
            ),
        ),
    ]
